# config file
TRAIN:
  ENABLE: True
  DATASET: tiny_coco2017
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  PREPROCESS: None
TEST:
  ENABLE: True
  DATASET: tini_coco2017
  BATCH_SIZE: 2
  PREPROCESS: None
MODEL:
  NUM_CLASSES: 80
  BACKBONE: resnet50
  MODEL_NAME: retina_net
  LOSS_FUNC: focal_loss
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
NUM_GPUS: 1
DATASET_DIR: /media/dat/68fa98f8-9d03-4c1e-9bdb-c71ea72ab6fa/dat/dataset/COCO_2
OUTPUT_DIR: ./output/resnet50
LOGS_DIR: ./logs/resnet50